# Generated by Django 3.2.7 on 2021-09-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VariableMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finanzas.variable')),
            ],
        ),
    ]
